specVersion: 0.2.0
name: parallel-streaming-subql
version: 1.0.0
description: ''
repository: 'https://github.com/parallel-finance/parallel-streaming-subql'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x5af9097d0e1c7a3b125a94c9579ca700490d337c655e1d72d05279b3b52253ae'
  endpoint: 'wss://staging-rpc.parallel.fi'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: crowdloans
