specVersion: 0.2.0
name: parallel-streaming-subql
version: 0.0.0
description: 'streaming subquery indexer feature via Heiko'
repository: 'https://github.com/parallel-finance/parallel-streaming-subql'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b'
  endpoint: 'wss://heiko-rpc.parallel.fi'
  dictionary: 'https://api.subquery.network/sq/subquery/parallel-heiko-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 924097
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: streaming
